Try new logic for skipping

diff --git a/.github/workflows/poetry-actions.yaml b/.github/workflows/poetry-actions.yaml
--- a/.github/workflows/poetry-actions.yaml
+++ b/.github/workflows/poetry-actions.yaml
@@ -67,8 +67,10 @@ jobs:
       - name: Check version on Test PyPI
         id: version-check
         run: |
-          RESPONSE=$(curl -s https://test.pypi.org/pypi/$PACKAGE_NAME/json)
-          if echo "$RESPONSE" | jq -r '.releases | keys | .[]' | grep -q "$VERSION"; then
+          PACKAGE_NAME=${{ env.PACKAGE_NAME }}
+          VERSION=${{ env.VERSION }}
+          RESPONSE=$(curl -s https://test.pypi.org/pypi/$PACKAGE_NAME/json || echo "error")
+          if [ "$RESPONSE" != "error" ] && echo "$RESPONSE" | jq -r '.releases | keys | .[]' | grep -q "$VERSION"; then
             echo "skip=true" >> $GITHUB_ENV
           else
             echo "skip=false" >> $GITHUB_ENV
@@ -114,8 +116,10 @@ jobs:
       - name: Check version on PyPI
         id: version-check
         run: |
-          RESPONSE=$(curl -s https://pypi.org/pypi/$PACKAGE_NAME/json)
-          if echo "$RESPONSE" | jq -r '.releases | keys | .[]' | grep -q "$VERSION"; then
+          PACKAGE_NAME=${{ env.PACKAGE_NAME }}
+          VERSION=${{ env.VERSION }}
+          RESPONSE=$(curl -s https://pypi.org/pypi/$PACKAGE_NAME/json || echo "error")
+          if [ "$RESPONSE" != "error" ] && echo "$RESPONSE" | jq -r '.releases | keys | .[]' | grep -q "$VERSION"; then
             echo "skip=true" >> $GITHUB_ENV
           else
             echo "skip=false" >> $GITHUB_ENV
